### ISSUE TITLE
NPE while trying to use the tool

### ISSUE THREAD

**Issue by vogella** [mickaelistria/eclipse-ide-parallel-builds-demo#1]
If I include the tool into a runtime Eclipse and try to measure the jde.core build times, I get lots of NPE.

!MESSAGE Errors running builder 'Java Builder' on project 'org.eclipse.jdt.core.ecj.validation'.
!STACK 0
java.lang.NullPointerException
	at org.eclipsecon.demo.parallelbuilds.LogBuildsListener.postBuild(LogBuildsListener.java:133)
	at org.eclipsecon.demo.parallelbuilds.Activator$1.println(Activator.java:50)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.build(JavaBuilder.java:251)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:834)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:228)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:271)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:324)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:327)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:379)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:400)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:145)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by mickaelistria** [comment]
The issue is caused by AutoBuild being on (I always disable it for testing). I'll fix it so no error happens at least.

**Comment by mickaelistria** [comment]
I've pushed a dummy patch, please try again.

**Comment by vogella** [comment]
Thanks @mickaelistria the NPE is gone. FYI - The result is hard to read, the gant chart overlaps with the text and I noticed that the reported build time goes done every time I trigger a clean build. 

![image](https://user-images.githubusercontent.com/139910/46622791-00f73280-cb2c-11e8-8b5c-4a9e175050fc.png)

**Comment by mickaelistria** [comment]
> the gant chart overlaps with the text

Please create a new issue for that.

> I noticed that the reported build time goes done every time I trigger a clean build.

I guess you mean "down".
In that case it's normal and expected and good. Both the JVM and the OS and the processor do a lot of optimization by "learning" from probable execution paths (remember the security issues caused by speculative execution). Also the classloading may affect the 1st build and not the next ones.
To compare results, it's necessary to restart the IDE and repeat very similar steps before triggering the build. I'll soon share a document reporting how parallel builds affects various projects; also in 2 weeks https://www.eclipsecon.org/europe2018/sessions/parallel-builds-eclipse-ide-workspace-value-making-and-optimal-usages
